# Generated by Django 3.1.1 on 2020-09-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguer',
            name='image',
            field=models.ImageField(default='uploads/hamburguer_defalt', upload_to='uploads/'),
        ),
    ]
