# Generated by Django 3.1.1 on 2020-09-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200905_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguer',
            name='image',
            field=models.ImageField(default='hamburguer_defalt.png', upload_to='images'),
        ),
    ]
