# Generated by Django 3.1.1 on 2020-09-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200906_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combohamburguer',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='combohamburguer',
            name='value',
        ),
        migrations.AddField(
            model_name='combohamburguer',
            name='image',
            field=models.ImageField(blank=True, default='defalt.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='combohamburguer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
