# Generated by Django 3.1.1 on 2020-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200906_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='defalt.png', upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type_bread', models.CharField(choices=[('Hamburguer', 'Hamburguer'), ('Batata Frita', 'Batata Frita'), ('Pastel', 'Pastel'), ('Bebidas', 'Bebidas'), ('Adicionais', 'Adicionais')], default='Hamburguer', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='ComboHamburguer',
            new_name='Combo',
        ),
        migrations.DeleteModel(
            name='Hamburguer',
        ),
    ]
