# Generated by Django 3.1.1 on 2020-09-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200926_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_bread',
            new_name='type_product',
        ),
    ]
